[workspace]
resolver = "3"
members = [
  "libs/build-info",
  "libs/build-info-macros",
  "libs/defy",
  "libs/graph",
  "libs/ids",
  "libs/puddle",
  "libs/slice-ext",
  "libs/unicase",
  "libs/uord",
  "libs/vector-type",
  "libs/yggdrasil"
]
