[package]
name = "winit-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0"
serde = { version = "1.0", optional = true, features = ["derive"] }
winit = ">=0.28.6"

[features]
serde = ["dep:serde", "winit/serde"]
