[package]
name = "winit-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0"
serde = { version = "1.0", optional = true }
winit = "*"

[features]
serde = ["dep:serde", "winit/serde"]
