[package]
name = "ids"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[dependencies]
serde = { version = "1.0", optional = true }
nohash-hasher = { version = "0.2.0" }

[features]
default = ["map"]
map = []
serde = ["dep:serde"]
